package pools

var nouns = []string{"man:manushya", "woman:mahile", "child:baalu", "person:vyakti", "boy:horalu", "girl:hole",
	"dog:naayi", "cat:bilu", "house:maneyu", "car:caru", "book:pushtaka", "table:mejeya",
	"chair:kursi", "pen:kalamu", "paper:haagu", "phone:phone", "computer:sampaadaka",
	"water:neeru", "food:ahara", "fruit:haalu", "vegetable:sabji", "apple:seebu",
	"banana:bananaa", "orange:kittale", "grape:draksha", "tree:baale", "flower:poo",
	"sun:surya", "moon:chandra", "star:taare", "sky:akaasha", "earth:bhumi",
	"river:nadi", "lake:keri", "mountain:raalu", "sea:sagara", "island:deepa",
	"city:nagara", "town:ooru", "village:haadi", "street:raaja", "road:rasta",
	"building:maneya", "school:vidhyaalaya", "college:mahavidyalaya", "university:visvavidyalaya",
	"hospital:aspataalu", "doctor:vaidyaru", "nurse:sevakara", "teacher:guruvu",
	"student:vidyarthi", "class:paathashaala", "work:kaarye", "job:padavi", "company:sansthe",
	"office:kaaryalaya", "market:saagalu", "shop:dukaan", "store:godi", "money:dhanam",
	"coin:thagadi", "note:paetra", "bank:kaanchipet", "credit card:kredit kaardu", "bill:bil",
	"ticket:ticket", "passport:paasaporta", "travel:yaatre", "bag:baagu", "shirt:shirtu",
	"pant:paat", "dress:vastra", "shoes:jootu", "hat:topi", "sock:sokku", "glove:haathu",
	"jacket:jacketu", "coat:koota", "tie:kaayi", "belt:paandu", "watch:ghadi", "glasses:kannadi",
	"ring:chandana", "earring:kannike", "necklace:hara", "bracelet:kaaya", "key:key",
	"door:daari", "window:jhaalu", "roof:chhat", "wall:baari", "floor:maati", "ceiling:parimaala",
	"light:belaku", "fan:paakhe", "air:haav", "sound:shabda", "voice:kaayike",
	"music:sangeeta", "song:haadu", "movie:cinema", "television:tv", "radio:raadiyo",
	"camera:kamera", "photo:chitra", "video:video", "game:krida", "sport:khel",
	"team:taim", "match:spardhe", "player:kheledaar", "coach:prashikshaka", "computer:sampaadaka",
	"mouse:makkaLu", "keyboard:keebord", "screen:scriin", "monitor:monitaru", "printer:printa",
	"text:textu", "book:pushtaka", "newspaper:patrike", "letter:patra", "magazine:patrikeyu",
	"novel:kathe", "article:lakshana", "chapter:adhyaaya", "paragraph:paaraagrapha", "sentence:vaakya",
	"word:shabda", "dictionary:shabdakosha", "language:bhaasha", "grammar:vyakaraNa", "speech:baashana",
	"alphabet:akshara", "vowel:swara", "consonant:vyanjana", "pronunciation:uchaarana", "accent:ucchaarana",
	"test:pariksha", "exam:pariksha", "question:prashne", "answer:uttara", "homework:ghareyavidhya",
	"assignment:kaaryapathra", "project:prakalpa", "presentation:prasthuti", "research:paathane",
	"study:adhyayana", "student:vidyarthi", "teacher:guruvu", "principal:mukhyaacharya", "school:vidhyaalaya",
	"classroom:paathashaala", "playground:kridamaidan", "library:pustakalaya", "canteen:kantheena", "gym:gym",
	"toilet:shauchalay", "bathroom:kupa", "kitchen:arojana", "bedroom:kaayipaatra", "living room:naaduvaLu",
	"dining room:upahara graha", "garden:baagilu", "yard:mannu", "garage:gaaraaj", "balcony:manjira",
	"roof:chhat", "basement:neerithale", "floor:maati", "wall:baari", "ceiling:parimaala",
	"window:jhaalu", "door:daari", "doormat:paati", "lock:kaatu", "key:key", "handle:haandilu",
	"furniture:sthaayi", "sofa:sophalu", "table:mejeya", "chair:kursi", "couch:sopha", "stool:kudi",
	"bookcase:pustakaraaj", "cupboard:kothi", "drawer:geya", "shelf:jalaya", "lightbulb:belaku"}
